version: '3.6'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
  subscriber:
    build:
      dockerfile: Dockerfile
      context: ./subscriber/
    container_name: subscriber
    depends_on:
      - postgres
  publisher:
    build:
      dockerfile: Dockerfile
      context: ./publisher/
    container_name: publisher
    depends_on:
      - subscriber
